image: maven:3-jdk-8

stages:
  - build

build:
  stage: build
  script:
    - mvn --batch-mode package
    - mvn --batch-mode verify

  cache:
    paths:
      - .m2

  artifacts:
    paths:
      - target/jenkins-nomad-plugin.hpi
